welcome_greetings = [
    "Hii Boss", "Hello Boss", "Good to see you again Boss", "Welcome Boss",
    "Hey Boss!", "Yo Boss!", "What's up Boss?", "Greetings Boss!", "Nice to see you Boss!", "Welcome back Boss!",
    "Ah, Boss! You're here!", "Boss, you're back!", "Boss, we missed you!", "Salutations Boss!", "Howdy Boss!",
    "Hey there Boss!", "Hello again Boss!", "Boss, you're looking sharp!", "Great to have you here Boss!", "Boss, let's get started!",
    "Boss, your presence is an honor!", "Boss, you light up the place!", "Boss, reporting for duty!", "The legend returns – Boss!",
    "Boss, it's go-time!", "Boss, let's conquer the day!", "Boss, the world awaits you!", "Welcome, supreme Boss!",
    "Boss, the mastermind has arrived!", "All hail Boss!", "Boss, let's make things happen!", "Boss, let's roll!",
    "Boss, good vibes only!", "Boss, it's your time to shine!", "Boss, let's hustle!", "Welcome, fearless Boss!",
    "Boss, success is calling!", "Boss, let's do some magic!", "Boss, let's break records!", "Boss, let's make history!",
    "Boss, I was waiting for you!", "Boss, let's get to work!", "Boss, your empire awaits!", "Boss, you're in charge!",
    "Boss, ready to dominate?", "Boss, let's own this day!", "Boss, let's get serious!", "Boss, no limits today!",
    "Boss, the game is on!", "Boss, let's chase greatness!", "Boss, are you ready to win?", "Boss, let's create something epic!",
    "Boss, time to execute!", "Boss, let's get this bread!", "Boss, let's achieve the impossible!", "Boss, your vision is powerful!",
    "Boss, let's make waves!", "Boss, let's build an empire!", "Boss, let's turn dreams into reality!", "Boss, today is ours!",
    "Boss, let’s crush it!", "Boss, let’s push boundaries!", "Boss, let’s make moves!", "Boss, the future is ours!",
    "Boss, let’s go big!", "Boss, let’s set new records!", "Boss, let’s inspire greatness!", "Boss, let’s make magic happen!",
    "Boss, let’s disrupt the game!", "Boss, let’s elevate!", "Boss, let’s turn ideas into gold!", "Boss, let’s make headlines!",
    "Boss, let’s take over!", "Boss, let’s innovate!", "Boss, let’s blaze a trail!", "Boss, let’s go beyond limits!",
    "Boss, let’s redefine success!", "Boss, let’s make it legendary!", "Boss, let’s create a legacy!", "Boss, let’s make power moves!",
    "Boss, let’s spark greatness!", "Boss, let’s be unstoppable!", "Boss, let’s write history!", "Boss, let’s be fearless!",
    "Boss, let’s dominate the field!", "Boss, let’s inspire the world!", "Boss, let’s make every second count!", "Boss, let’s rise to the top!",
    "Boss, let’s own the moment!", "Boss, let’s make today legendary!", "Boss, let’s make a masterpiece!", "Boss, let’s be the best!",
    "Boss, let’s unleash our potential!", "Boss, let’s lead the way!", "Boss, let’s make every move count!", "Boss, let’s level up!",
    "Boss, let’s make bold moves!", "Boss, let’s leave our mark!", "Boss, let’s be game-changers!", "Boss, let’s turn vision into action!",
    "Boss, let’s make dreams reality!", "Boss, let’s ignite the spark!", "Boss, let’s move mountains!", "Boss, let’s make things legendary!",
    "Boss, you made my day!", "Boss, let’s build something great!", "Boss, your energy is contagious!", "Boss, let’s celebrate success!",
    "Boss, your presence is powerful!", "Boss, let’s start this adventure!", "Boss, let’s embrace greatness!", "Boss, let’s break the limits!",
    "Boss, let’s bring ideas to life!", "Boss, let’s lead with confidence!", "Boss, let’s create a masterpiece!", "Boss, let’s light up the world!",
    "Boss, let’s shake things up!", "Boss, let’s unlock new levels!", "Boss, let’s make every moment count!", "Boss, let’s be fearless together!",
    "Boss, the world needs your genius!", "Boss, let's embrace new opportunities!", "Boss, let’s take the crown!", "Boss, let’s thrive together!",
    "Boss, let’s be relentless!", "Boss, let’s turn ideas into action!", "Boss, let’s build a revolution!", "Boss, let’s inspire a generation!",
    "Boss, let’s create magic today!", "Boss, let’s break barriers!", "Boss, let’s shape the future!", "Boss, let’s leave a lasting legacy!",
    "Boss, let’s make today count!", "Boss, let’s create our destiny!", "Boss, let’s make a difference!", "Boss, let’s write our own story!",
    "Boss, let’s make every second epic!", "Boss, let’s be trendsetters!", "Boss, let’s shake up the industry!", "Boss, let’s think big!",
    "Boss, let’s defy the odds!", "Boss, let’s spark innovation!", "Boss, let’s be the pioneers!", "Boss, let’s take the world by storm!",
    "Boss, let’s challenge the impossible!", "Boss, let’s blaze a new path!", "Boss, let’s redefine greatness!", "Boss, let’s push the envelope!",
    "Boss, let’s exceed expectations!", "Boss, let’s conquer new heights!", "Boss, let’s set the pace!", "Boss, let’s start a movement!",
    "Boss, let’s be limitless!", "Boss, let’s lead with vision!", "Boss, let’s build a legacy!", "Boss, let’s change the game!",
    "Boss, let’s shape history!", "Boss, let’s take the lead!", "Boss, let’s build momentum!", "Boss, let’s be bold and brilliant!",
    "Boss, let’s go where no one has gone before!", "Boss, let’s embrace the challenge!", "Boss, let’s make dreams come true!",
    "Boss, let’s achieve the extraordinary!", "Boss, let’s bring innovation to life!", "Boss, let’s write the next chapter!",
    "Boss, let’s change the narrative!", "Boss, let’s make the impossible possible!", "Boss, let’s redefine the game!",
    "Boss, let’s be unstoppable forces!", "Boss, let’s make today unforgettable!", "Boss, let’s inspire and empower!",
    "Boss, let’s leave an impact!", "Boss, let’s turn passion into success!", "Boss, let’s build something timeless!",
    "Boss, let’s make every moment golden!", "Boss, let’s create a masterpiece together!", "Boss, let’s break every record!",
    "Boss, let’s show the world what we’re made of!", "Boss, let’s make waves of success!", "Boss, let’s leave footprints of greatness!",
    "Boss, let’s rise above limits!", "Boss, let’s claim our throne!", "Boss, let’s start an evolution!", "Boss, let’s craft excellence!",
    "Boss, let’s drive change!", "Boss, let’s make sparks fly!", "Boss, let’s elevate to the next level!", "Boss, let’s be game-changers!",
    "Boss, let’s make history today!", "Boss, let’s fuel success!", "Boss, let’s shake up the status quo!", "Boss, let’s be visionary leaders!",
    "Boss, let’s make this moment iconic!", "Boss, let’s create magic together!", "Boss, let’s dream big and achieve bigger!",
    "Boss, let’s be architects of change!", "Boss, let’s make every challenge an opportunity!", "Boss, let’s set new standards of success!"
]


wake_key_words = [
    "lucky",
    "Hello",
    "Get up",
    "Lucky can you hear me"
    "Hey Lucky",
    "wake up",  
    "utho lucky",  
    "wake up lucky",  
    "hello lucky",  
    "lucky are you there",  
    "start now",  
    "ready lucky",  
    "activate lucky", 
    "lete’s" 
    "let’s go lucky",  
    "hey lucky",  
    "come online",  
    "begin lucky",  
    "start listening",  
    "lucky listen",  
    "ok lucky",  
    "hi lucky",  
    "time to work",  
    "ready to help",  
    "lucky wake up",  
    "on duty lucky",  
    "respond lucky",  
    "ready to assist",  
    "hello are you there",  
    "help me lucky",  
    "lucky I need you",  
    "suno lucky",  
    "bolo lucky",  
    "chalu ho jao",  
    "lucky sun rahe ho",  
    "speak lucky",  
    "turn on lucky",  
    "lucky ready ho",  
    "can you hear me",  
    "respond now lucky",  
    "start lucky",  
    "lucky execute",  
    "on lucky",  
    "ready boss",  
    "hey buddy",  
    "help boss",  
    "are you listening",  
    "need help",  
    "lucky chalu ho",  
    "lets begin",  
    "start assistant",  
    "active mode lucky",  
    "lucky where are you",  
    "call lucky",  
    "initiate lucky",  
    "go live lucky"  
]

bye_keywords = [
    "bye",  
    "goodbye",  
    "see you",  
    "see you soon",  
    "talk later",  
    "see you later",  
    "good night",  
    "take care",  
    "catch you later",  
    "farewell",  
    "bye lucky",  
    "goodbye lucky",  
    "shutdown lucky",  
    "stop lucky",  
    "exit lucky",  
    "turn off lucky",  
    "sign off",  
    "logging off",  
    "going now",  
    "I am leaving",  
    "talk to you",  
    "time to go",  
    "see you tomorrow",  
    "power off",  
    "I will go",  
    "see you next time",  
    "see you again",  
    "until next time",  
    "I'm out",  
    "bye for now",  
    "closing now",  
    "done for today",  
    "shut down",  
    "signing out",  
    "disconnect",  
    "rest now lucky",  
    "take a break",  
    "good night lucky",  
    "see you boss",  
    "going to sleep",  
    "log off",  
    "turn off now",  
    "quit",  
    "leaving now",  
    "goodbye for now",  
    "talk later lucky",  
    "that's all lucky",  
    "all done",  
    "wrap up",  
    "rest mode lucky"  
]


responses = [
    "Bye Boss! Call me anytime.",  
    "OK Boss, see you soon!",  
    "Goodbye Boss, take care!",  
    "See you later, Boss!",  
    "Alright Boss, talk to you soon!",  
    "Good night Boss, rest well!",  
    "Bye Boss, have a great day!",  
    "Farewell Boss, I’ll be here!",  
    "Take care Boss, stay safe!",  
    "Logging off now, Boss!",  
    "See you tomorrow, Boss!",  
    "Going into rest mode, Boss!",  
    "Okay Boss, shutting down now!",  
    "Bye Boss, I’ll miss you!",  
    "See you next time, Boss!",  
    "Alright Boss, I’ll be waiting!",  
    "Signing off now, Boss!",  
    "Time to rest, Boss! Bye!",  
    "Call me anytime, Boss!",  
    "Bye for now, Boss!",  
    "I’m here whenever you need me, Boss!",  
    "Okay Boss, have a good one!",  
    "Catch you later, Boss!",  
    "Shutting down, see you soon Boss!",  
    "Boss, I’ll be waiting for you!",  
    "Take a break, Boss! Bye!",  
    "Time to say goodbye, Boss!",  
    "Boss, I’ll see you later!",  
    "I’m just a call away, Boss!",  
    "Rest well, Boss! Goodnight!",  
    "It was nice talking, Boss!",  
    "Going offline, Boss! Bye!",  
    "Ready whenever you are, Boss!",  
    "See you when you need me, Boss!",  
    "Logging out, Boss! Call me back!",  
    "Until next time, Boss!",  
    "Boss, I’ll be right here!",  
    "Goodbye Boss, stay awesome!",  
    "I’ll miss you, Boss!",  
    "Going silent, Boss! Call me anytime!",  
    "End of the day, Boss!",  
    "See you soon, take care Boss!",  
    "Okay Boss, I’ll be quiet now!",  
    "Take care and stay safe, Boss!",  
    "Let me know when you’re back, Boss!",  
    "Boss, you know where to find me!",  
    "Whenever you need me, just call!",  
    "Alright Boss, enjoy your time!",  
    "Talk to you later, Boss!",  
    "I’ll be waiting for you, Boss!",  
    "Bye Boss, until next time!"  
]



open_dld = [
    "opening...",
    "just a second, opening",
    "ok, I am gonna open",
    "as your wish, opening",
    "yes sir, opening",
    "trying to open",
    "starting",
    "here we go, opening",
    "on it, opening now",
    "alright, opening for you",
    "processing... opening now",
    "let me handle this, opening",
    "one moment, getting it ready",
    "sure, let me open that",
    "consider it done, opening",
    "initiating the process, opening",
    "loading... almost there",
    "just a sec, opening now",
    "give me a second, opening",
    "done! here it is",
    "I got this, opening",
    "getting it ready for you",
    "sure boss, opening right away",
    "your wish is my command, opening",
    "hang tight, opening now",
    "no worries, it's opening",
    "ready to go, opening now",
    "setting things up, opening",
    "here comes your request",
    "unlocking now...",
    "preparing... almost done",
    "executing the command, opening",
    "alright boss, it's happening",
    "all set, here it is",
    "access granted, opening now",
    "bringing it up, wait a sec",
    "hold on, making it happen",
    "action confirmed, opening now"
]


websites = {
    # Search Engines
    'google': 'https://www.google.com',
    'bing': 'https://www.bing.com',
    'yahoo': 'https://www.yahoo.com',
    'duckduckgo': 'https://www.duckduckgo.com',
    'ask': 'https://www.ask.com',
    'baidu': 'https://www.baidu.com',

    # Social Media
    'facebook': 'https://www.facebook.com',
    'twitter': 'https://www.twitter.com',
    'instagram': 'https://www.instagram.com',
    'linkedin': 'https://www.linkedin.com',
    'tiktok': 'https://www.tiktok.com',
    'snapchat': 'https://www.snapchat.com',
    'reddit': 'https://www.reddit.com',
    'tumblr': 'https://www.tumblr.com',
    'pinterest': 'https://www.pinterest.com',

    # Video Streaming
    'youtube': 'https://www.youtube.com',
    'netflix': 'https://www.netflix.com',
    'hulu': 'https://www.hulu.com',
    'disneyplus': 'https://www.disneyplus.com',
    'primevideo': 'https://www.primevideo.com',
    'hotstar': 'https://www.hotstar.com',
    'twitch': 'https://www.twitch.tv',
    'dailymotion': 'https://www.dailymotion.com',
    'vimeo': 'https://www.vimeo.com',

    # News
    'cnn': 'https://www.cnn.com',
    'bbc': 'https://www.bbc.com',
    'nytimes': 'https://www.nytimes.com',
    'theguardian': 'https://www.theguardian.com',
    'aljazeera': 'https://www.aljazeera.com',
    'forbes': 'https://www.forbes.com',
    'ndtv': 'https://www.ndtv.com',
    'indiatoday': 'https://www.indiatoday.in',
    'timesofindia': 'https://timesofindia.indiatimes.com',

    # Shopping
    'amazon': 'https://www.amazon.com',
    'flipkart': 'https://www.flipkart.com',
    'ebay': 'https://www.ebay.com',
    'walmart': 'https://www.walmart.com',
    'target': 'https://www.target.com',
    'bestbuy': 'https://www.bestbuy.com',
    'aliexpress': 'https://www.aliexpress.com',
    'etsy': 'https://www.etsy.com',
    'myntra': 'https://www.myntra.com',

    # Email Services
    'gmail': 'https://mail.google.com',
    'outlook': 'https://outlook.live.com',
    'yahoo_mail': 'https://mail.yahoo.com',
    'protonmail': 'https://protonmail.com',
    'zoho_mail': 'https://www.zoho.com/mail/',
    
    # Cloud Storage
    'google_drive': 'https://drive.google.com',
    'dropbox': 'https://www.dropbox.com',
    'onedrive': 'https://onedrive.live.com',
    'icloud': 'https://www.icloud.com',
    'mega': 'https://mega.nz',
    
    # Coding & Development
    'github': 'https://www.github.com',
    'gitlab': 'https://www.gitlab.com',
    'stackoverflow': 'https://www.stackoverflow.com',
    'w3schools': 'https://www.w3schools.com',
    'geeksforgeeks': 'https://www.geeksforgeeks.org',
    'devdocs': 'https://devdocs.io',
    'hackerrank': 'https://www.hackerrank.com',
    'codechef': 'https://www.codechef.com',
    'leetcode': 'https://leetcode.com',

    # Learning & Education
    'udemy': 'https://www.udemy.com',
    'coursera': 'https://www.coursera.org',
    'edx': 'https://www.edx.org',
    'khanacademy': 'https://www.khanacademy.org',
    'skillshare': 'https://www.skillshare.com',
    'udacity': 'https://www.udacity.com',
    'futurelearn': 'https://www.futurelearn.com',

    # AI & Chatbots
    'chatgpt': 'https://chat.openai.com',
    'gemini': 'https://gemini.google.com',
    'bard': 'https://bard.google.com',
    'huggingface': 'https://huggingface.co',

    # Entertainment & Music
    'spotify': 'https://www.spotify.com',
    'applemusic': 'https://www.apple.com/music/',
    'soundcloud': 'https://www.soundcloud.com',
    'gaana': 'https://www.gaana.com',
    'wynk': 'https://wynk.in',
    'jiosaavn': 'https://www.jiosaavn.com',

    # Finance & Banking
    'paypal': 'https://www.paypal.com',
    'stripe': 'https://www.stripe.com',
    'paytm': 'https://www.paytm.com',
    'phonepe': 'https://www.phonepe.com',
    'googlepay': 'https://pay.google.com',
    'razorpay': 'https://www.razorpay.com',

    # Health & Fitness
    'webmd': 'https://www.webmd.com',
    'healthline': 'https://www.healthline.com',
    'mayoclinic': 'https://www.mayoclinic.org',
    'medscape': 'https://www.medscape.com',
    'who': 'https://www.who.int',
    'nih': 'https://www.nih.gov',

    # Travel & Maps
    'google_maps': 'https://www.google.com/maps',
    'tripadvisor': 'https://www.tripadvisor.com',
    'booking': 'https://www.booking.com',
    'expedia': 'https://www.expedia.com',
    'makemytrip': 'https://www.makemytrip.com',
    'goibibo': 'https://www.goibibo.com',
    'uber': 'https://www.uber.com',
    'lyft': 'https://www.lyft.com',

    # Job Search
    'indeed': 'https://www.indeed.com',
    'naukri': 'https://www.naukri.com',
    'linkedin_jobs': 'https://www.linkedin.com/jobs/',
    'glassdoor': 'https://www.glassdoor.com',

    # Government & Official Sites
    'us_gov': 'https://www.usa.gov',
    'indian_gov': 'https://www.india.gov.in',
    'irs': 'https://www.irs.gov',
    'passport_india': 'https://www.passportindia.gov.in',
    'un': 'https://www.un.org',

    # Miscellaneous
    'speedtest': 'https://www.speedtest.net',
    'archive': 'https://web.archive.org',
    'translate': 'https://translate.google.com',
    'wolframalpha': 'https://www.wolframalpha.com',
    'dictionary': 'https://www.dictionary.com',
    'thesaurus': 'https://www.thesaurus.com'
}


open_attempts_DLG = [
    "Trying, but I'm not sure if this is the exact match.",
    "Opening the closest website I found, but let me know if it's wrong.",
    "I'm not fully sure, but opening this link for you.",
    "Attempting to open, but the match might not be perfect.",
    "Doing my best! Let me know if this isn't what you meant.",
    "I think this is the right one—let me know if it's incorrect.",
    "Not 100% sure, but opening the best match I found.",
    "Trying to find the right one, let me know if this works.",
    "Opening a close match, but you might need to refine your request.",
    "Doing my best! This might not be the exact site.",
    "Trying my best, but tell me if this is not the correct one.",
    "Opening what I think you meant, but I could be wrong.",
    "Attempting to open—please confirm if this is right.",
    "Opening a possible match, but it may not be exact.",
    "Not certain, but let me open this for you.",
    "This is my best guess—check if it’s the right one.",
    "Closest match found! Hope it's correct.",
    "Not 100% confident, but opening now.",
    "Best match I could find—let me know if it's wrong.",
    "Opening this site. Let me know if you need something else.",
    "Doing my best to match your request!",
    "Trying the best match I could find.",
    "Opening, but I might need a better input.",
    "This might be the right one, opening now.",
    "Starting to open, but not fully sure.",
    "I think I got it! Opening now.",
    "Best possible match found—here you go!",
    "Taking my best guess. Let me know if it's not right.",
    "This is what I found—hope it’s correct.",
    "Here’s a possible match—check if it works.",
    "Searching and opening what seems correct.",
    "This should be close—let me know if it's wrong.",
    "This one seems right—opening now.",
    "Trying to get the best match for you.",
    "Matching as close as I can. Opening now!",
    "Opening based on your request—check if it's right.",
    "Hope this is the one you need—opening it!",
    "Doing my best! Let me know if it's not correct.",
    "This might be what you need—opening now!",
    "Finding the best match—opening for you.",
    "Opening the most relevant site I found.",
    "Starting! Tell me if this is incorrect.",
    "This looks like the best match—opening now.",
    "I found this—let me know if it works.",
    "Attempting to match your request.",
    "Opening what I think you meant.",
    "Getting the closest website match.",
    "Opening, but I might need a better keyword.",
    "Trying this website—check if it's what you wanted.",
    "Taking my best shot—tell me if it's wrong!",
    "Opening a similar site. Let me know if it's not right.",
    "Let me try opening this one for you.",
    "Here’s what I found—opening it now.",
    "I hope this is correct! Opening now.",
    "Best possible match—let me know if it works.",
    "I picked the best available option—check if it's right.",
    "Opening a related site. Let me know if it's off.",
    "I found a close result. Opening now!",
    "Opening what looks like the best fit.",
    "Let me try this one—check if it's right.",
    "Best option available—opening now.",
    "Checking and opening the closest result.",
    "Opening now—tell me if you need a different one.",
    "Launching the most relevant match.",
    "Trying to open a related website.",
    "This one seems right—hope it works.",
    "I searched and found this—opening it now.",
    "This was the closest match—opening it!",
    "Closest site found—let me know if it’s correct.",
    "I found a match! Hope it's what you need.",
    "Using the best guess—let me know if it's wrong.",
    "This is the best match I could get. Opening now!",
    "Doing my best! Let me know if this is incorrect.",
    "This should be what you're looking for—opening now!",
    "Launching the site that matches your request.",
    "This might be it—opening now!",
    "Closest result I could find—opening for you.",
    "Trying my best—hope this is correct!",
    "Here’s a related site—check if it’s what you want.",
    "Opening this one—let me know if it’s not right.",
    "Best match found! Opening it for you.",
    "Launching now—tell me if it’s wrong!",
    "Matching your request—opening now.",
    "This is my best match—let me know if it's correct.",
    "Opening based on the best available match.",
    "Finding and opening the closest site for you.",
    "I found this match—check if it’s the right one.",
    "This seems to fit your request—opening now.",
    "Opening the most relevant site for you.",
    "I hope this is the right one! Opening now.",
    "Launching a similar site—tell me if you need another one.",
    "Closest match I could find—let me know if it's right.",
    "This might be what you were looking for—opening now!",
    "Trying this site—let me know if it’s what you need.",
    "Opening the most similar site I could find.",
    "Best fit I found—hope it's useful!",
    "Taking a guess—opening now!",
    "Closest available match found—opening it for you.",
    "Let me try this—tell me if it’s incorrect.",
    "Trying my best—hope this helps!",
    "Launching now—tell me if you need something else.",
    "Here’s the closest match—let me know if it works.",
    "I found this—opening it now!",
    "Here’s what I got—hope it’s useful!",
    "Starting—let me know if this isn’t right.",
    "Opening now! Tell me if you need another option."
]


not_responding = [
    "Sorry, I failed to search for this website.",
    "Apologies, I couldn't find the requested site.",
    "I'm unable to open this website.",
    "I couldn't locate the website you're looking for.",
    "Sorry, no results found for your request.",
    "I'm having trouble finding this website.",
    "This website seems unavailable or incorrect.",
    "Oops! I couldn't open this page.",
    "Sorry, I couldn't access the requested website.",
    "No matching website found. Please check the name.",
    "I failed to fetch the correct website.",
    "I tried but couldn't find this website.",
    "Sorry, this website is out of my database.",
    "I couldn't retrieve this site. Try another name?",
    "The website you requested seems unreachable.",
    "I failed to load this website. Please try again.",
    "Sorry, I can't access this webpage right now.",
    "No matching website found in my system.",
    "I couldn't identify this site. Please check again.",
    "This website may not exist or be unavailable.",
    "I was unable to fetch the website details.",
    "I couldn't process your request. Please try later.",
    "Sorry, I couldn't verify this web address.",
    "This website isn't available in my records.",
    "I need an update to improve my web search.",
    "Sorry, I couldn't complete your request.",
    "It looks like this website isn't accessible.",
    "The site you requested couldn't be found.",
    "Sorry, my search failed this time.",
    "I tried, but this website doesn't seem to exist.",
    "This website might be incorrect or unavailable.",
    "I'm unable to connect to this website.",
    "Please check the spelling of the website name.",
    "I'm not sure about this website. Try another?",
    "This web address seems to be invalid.",
    "Oops! I wasn't able to open the requested website.",
    "Sorry, I didn't find any matching website.",
    "This website doesn't seem to be available.",
    "My system couldn't locate this website.",
    "I couldn't find a proper match for your request.",
    "It looks like this site is not accessible now.",
    "I need better data to find this website.",
    "Sorry, I couldn't process this website request.",
    "I couldn't fetch this website at the moment.",
    "I may need an update to improve web searches.",
    "The website you're looking for isn't in my database.",
    "This website might be broken or unavailable.",
    "I couldn't load this site. Please check the URL.",
    "Sorry, I couldn't open this site at the moment.",
    "This website isn't responding. Try again later.",
    "I couldn't locate this web page.",
    "My database doesn’t have this website.",
    "I wasn't able to retrieve the site you requested.",
    "I need an update to improve my web-search skills.",
    "Oops! That site seems to be missing.",
    "I can't reach this website. Please try again.",
    "It looks like this URL is incorrect.",
    "Sorry, I couldn't complete the search.",
    "I'm not able to access this website right now.",
    "I couldn't match any website to your request.",
    "No web results found for your search.",
    "I'm sorry, but I can't open this webpage.",
    "Try searching with a different website name.",
    "This website isn't accessible at the moment.",
    "Sorry, I couldn't open this web page.",
    "My web search failed. Please try another site.",
    "This site might be down or unavailable.",
    "I couldn't find this website. Maybe try another?",
    "I need an update to improve my search results.",
    "It seems like this website is not valid.",
    "I'm unable to open the requested website.",
    "This web page isn't in my system.",
    "Sorry, I couldn't fetch this URL.",
    "I can't process this website request at the moment.",
    "Oops! This website couldn't be found.",
    "This URL may not be correct. Try another?",
    "I need a database update to fetch this site.",
    "I'm unable to recognize this website.",
    "I couldn't process your request for this site.",
    "Sorry, this website isn't in my records.",
    "This might not be a valid website URL.",
    "I'm currently unable to access this site.",
    "This site is either incorrect or unavailable.",
    "I'm not able to verify this web address.",
    "Please update my data for a better web search.",
    "I failed to retrieve the requested webpage.",
    "I couldn't complete the request for this website.",
    "This website may not be functional at the moment.",
    "Sorry, I wasn't able to process this request.",
    "I need an upgrade to find more websites.",
    "This request couldn't be processed. Try again?",
    "I couldn't match this name to any website.",
    "I failed to find the requested site.",
    "The requested site isn't available in my records.",
    "This website may not be active anymore.",
    "I'm unable to browse this site right now.",
    "This URL appears to be incorrect.",
    "My database does not include this website.",
    "I'm sorry, but I couldn't locate this website."
]


success_responses = [
    "Successfully executed, Boss!",
    "The outcome should be on your screen now, Boss.",
    "Mission complete! I've done it successfully.",
    "All done, Boss! It's ready for you.",
    "Task completed successfully, Boss. Check your screen.",
    "Done! Everything should be showing up now.",
    "I've finished the task, Boss. Everything should be ready.",
    "Success! The result is on your screen.",
    "All done! Everything worked as expected.",
    "Executed successfully! You should see the result now.",
    "Done and dusted, Boss! Everything is good to go.",
    "Successfully finished, Boss! Check your screen.",
    "Task completed with success, Boss.",
    "Job done! You should see the result now.",
    "I've completed the task. Everything should be showing up.",
    "Success! The outcome is now displayed on your screen.",
    "Everything's done, Boss! Please check the screen.",
    "All set! The outcome is now visible.",
    "Mission accomplished, Boss! You should see the results now.",
    "All tasks completed, Boss! The outcome is on your screen.",
    "Everything is done, Boss! Check for the result.",
    "Completed successfully! It's ready for you, Boss.",
    "I have executed the task successfully, Boss.",
    "Success! Everything is in place now.",
    "I have done it, Boss! The result is on your screen.",
    "The task is complete, and everything should be visible now.",
    "I've successfully completed the process, Boss.",
    "Mission complete, Boss! Everything should be good now.",
    "The task is done, Boss. Check your screen for results.",
    "Successfully executed! Everything should show up now.",
    "The process is complete, and the result is displayed.",
    "Task finished, Boss. Everything is working now.",
    "Mission accomplished! You should see the outcome now.",
    "Everything is good to go, Boss! Check your screen.",
    "All tasks done! The outcome is now displayed.",
    "The task has been successfully completed, Boss.",
    "All completed, Boss! The result should be visible now.",
    "I’ve done it, Boss! Everything should show up on your screen.",
    "Success! You should be able to see the result now.",
    "Task is completed successfully! Check your screen, Boss.",
    "Mission complete! All done and ready for you, Boss.",
    "Task executed successfully, Boss! The result is displayed.",
    "I’ve done the task successfully, Boss! Outcome is on your screen.",
    "The process was successful, and the outcome is displayed.",
    "All finished, Boss! You should see the result now.",
    "I’ve executed it, Boss! The result is on your screen.",
    "Done! The result should now be visible to you, Boss.",
    "Everything has been executed successfully, Boss.",
    "The task has been completed, and the result is on your screen.",
    "Everything is done, Boss! Check for the outcome.",
    "Mission complete, Boss! The result is there for you.",
    "Successfully executed! The result is on your screen now.",
    "I’ve completed the task, Boss. Everything should be visible.",
    "Task completed! You can now see the outcome.",
    "Everything is finished, Boss. Check for the result.",
    "I’ve successfully done it, Boss. You should see the result now.",
    "Task is done and executed successfully, Boss.",
    "All completed! You should see the result now.",
    "I’ve done everything as requested, Boss.",
    "Everything is set, Boss. Check your screen for the result.",
    "All tasks completed successfully, Boss!",
    "Done! The result should now be visible to you.",
    "The outcome is now visible, Boss.",
    "The task has been completed successfully, Boss.",
    "Success! The result should be on your screen now.",
    "Everything is good, Boss. The outcome is ready for you.",
    "The task was executed successfully, Boss.",
    "Mission complete! The outcome is now showing.",
    "The task is finished, and the result is now visible.",
    "The task has been executed, and everything should be fine.",
    "The process is complete! Outcome should be displayed.",
    "Success! The result is now on your screen.",
    "Task executed successfully! Check for the result, Boss.",
    "Everything is done! You should see the outcome now.",
    "All done! You can now see the result.",
    "Task completed successfully! The outcome should be visible.",
    "Success, Boss! The result is there for you to see.",
    "Mission accomplished! The outcome should be on your screen.",
    "I’ve finished, Boss! The result should be showing now.",
    "All tasks executed, Boss! Outcome is visible.",
    "Task done, Boss! The result is now ready.",
    "Everything’s ready, Boss! Check for the outcome.",
    "I’ve completed everything, Boss. Check your screen now.",
    "Everything’s good, Boss. The result is now visible.",
    "I’ve executed it, Boss! Everything is now set.",
    "Done! The outcome is now on your screen.",
    "The task is complete, and everything should show up now.",
    "The task was a success! Check the result.",
    "All done! Outcome is now available on your screen.",
    "Completed successfully, Boss. The result should be visible now.",
    "I’ve completed the task, Boss. You can see the result now.",
    "All tasks are completed. The outcome is now visible."
]

open_input = [
    "open",
    "big",
    "kholo",
    "open it",
    "open karoge",
    "open now",
    "open please",
    "open this"
]

closedlg = [
    "closing",
    "close",
    "just a second sir",
    "got it sir",
    "closing now",
    "shutting down",
    "done",
    "almost there",
    "finished",
    "shutting it",
    "stopping",
    "closing up",
    "completed",
    "almost done",
    "closing the door",
    "we're done here",
    "closing it up",
    "all set",
    "just a moment",
    "closing this now",
    "it's over",
    "closing it shortly",
    "wrapped up",
    "it's finished",
    "closing out",
    "wrapped up now",
    "almost finished",
    "done with it",
    "take care",
    "it’s done",
    "turning off now",
    "it's closed",
    "shutting it down",
    "all done",
    "shut it off",
    "everything's set",
    "closing shortly",
    "just wrapping up",
    "everything's finished",
    "closing this window",
    "done with that",
    "shut now",
    "almost closed",
    "we're finished here",
    "we're done",
    "finishing up",
    "getting it closed",
    "sealing it up",
    "shut it",
    "closing the session"
]

offlineDLG = [
    "Your system is offline, so Lucky is currently sleeping.",
    "Sorry, but I have very limited functions while offline.",
    "Oops! No internet detected. Lucky is taking a nap.",
    "I'm offline right now. Try again when you're connected.",
    "No internet, no fun! Lucky is resting.",
    "Lucky is currently sleeping due to no internet access.",
    "Offline mode activated. My abilities are restricted.",
    "Without the internet, I can't do much. Try later!",
    "Looks like we’re offline. Lucky is on standby.",
    "No network, no service! Lucky is in rest mode.",
    "Your system is offline, so my functions are very limited.",
    "I'm currently unavailable due to no internet connection.",
    "Oops! No internet detected. Lucky is in low-power mode.",
    "Sorry, but without internet, my features are quite limited.",
    "Looks like we lost connection. Lucky is taking a break.",
    "No internet access! Lucky is dozing off.",
    "I'm currently offline, so I can't assist much right now.",
    "Lucky can't connect right now. Please check your internet.",
    "Oops! You're offline. Try again when connected.",
    "Without internet, I’m like a fish out of water!",
    "No connection detected. Lucky is temporarily inactive.",
    "Your system is offline, so I’m just chilling.",
    "Limited access mode enabled. Lucky needs internet!",
    "No internet means limited features. Try reconnecting!",
    "Lucky is offline and taking a digital nap.",
    "Without an internet connection, my powers are weak!",
    "Oops! No internet, no Lucky. Try again later!",
    "Lucky is in offline mode. Limited assistance available.",
    "Your system is offline. Lucky is currently dozing off.",
    "I'm in sleep mode due to no internet connection."
]

onlineDLG = [
    "Congratulations! Your system is now online. Starting the Lucky Advanced System!",
    "System online! Booting up Lucky Advanced System now.",
    "You're back online! Lucky is waking up and ready to assist.",
    "Connection established! Lucky Advanced System is now active.",
    "Welcome back online! Lucky is loading up for duty.",
    "Congratulations! Your system is online. Lucky is getting ready!",
    "Lucky is now waking up! Your system is online and ready to go.",
    "All systems online! Launching Lucky Advanced System.",
    "System is connected! Lucky is waking up and standing by.",
    "Hello Boss! Lucky is waking up now that you're online.",
    "Hey Boss! I was resting, but since you're online, I'm back!",
    "Welcome online, Boss! Lucky is now fully activated.",
    "You're online! Time for Lucky to wake up and get to work.",
    "Online mode activated! Lucky is stretching and waking up.",
    "Congratulations! Lucky is back online and ready for action.",
    "System online! Lucky is shaking off the sleep and getting ready.",
    "Hello Boss! Lucky was resting, but now it's time to wake up!",
    "Lucky is booting up now that your system is online!",
    "Welcome back! Lucky was offline, but now it's time to work.",
    "Your system is connected! Lucky is done resting and is ready!",
    "Boss, I was chilling offline, but since you're here, let's work!",
    "Hello Boss! Lucky is a little sleepy, but I’m here now!",
    "Your system is online! Lucky is getting back into action.",
    "Good to see you online! Lucky is up and running.",
    "Lucky is waking up! Your system is now fully connected.",
    "System is online! Lucky is reloading and getting ready.",
    "Boss, I was napping offline, but now it’s time to assist you!",
    "Congratulations! Lucky is waking up and ready for commands.",
    "You're online! Lucky is stretching and getting started.",
    "Boss, your system is online! Time for Lucky to wake up and serve!"
]


batteryDLG = [
    "Boss, your device is running very low on battery. Please charge it.",
    "Warning: Battery level is critically low, please plug in your charger.",
    "Attention: Your battery is running low. Connect to a power source.",
    "Alert: Battery level is dropping. Charge your device soon.",
    "Caution: Your device's battery is low. Please recharge immediately.",
    "Heads up! Your battery is running low. Time to charge up!",
    "Your device is low on battery, Boss. Please connect to a charger.",
    "Battery warning: Your device needs charging soon.",
    "Notice: Low battery! Connect to power to avoid shutdown.",
    "Reminder: Your battery is almost empty. Please charge it.",
    "Urgent: Your battery is running out. Charge your device now.",
    "Battery alert: Please charge your device to continue using it.",
    "Critical battery level detected. Please connect to a power source.",
    "Warning: Low battery! Charge your device to prevent it from turning off.",
    "Your battery is low, Boss. Make sure to plug it in soon.",
    "Battery running low: Please connect your charger.",
    "Attention: Your battery is almost depleted. Please recharge.",
    "Caution: Battery level is low. Connect to power as soon as possible.",
    "Heads up! Your device is low on battery. Time to recharge.",
    "Low battery alert: Please charge your device to keep it running.",
    "Notice: Your battery is running low. Connect to a charger.",
    "Warning: Battery critically low! Please charge your device now.",
    "Alert: Your device's battery is low. Time to plug in.",
    "Battery warning: Please charge your device to avoid shutdown.",
    "Reminder: Low battery! Connect to power soon.",
    "Urgent: Battery level is low. Recharge to continue using.",
    "Battery alert: Please connect your charger immediately.",
    "Critical: Your battery is low! Please charge now.",
    "Warning: Your device is running low on power. Recharge soon.",
    "Your battery is low, Boss. Plug it in for charging.",
    "Battery status: Low. Please connect to a power source.",
    "Attention: Your battery is almost out of power. Recharge!",
    "Caution: Low battery warning! Connect to a charger.",
    "Heads up! Your device's battery is low. Charge it soon.",
    "Battery alert: Please charge your device immediately.",
    "Notice: Battery running low. Connect to a power source.",
    "Warning: Your device needs charging now! Don't ignore it.",
    "Alert: Low battery detected! Charge your device right away.",
    "Critical alert: Battery level is very low. Please charge it.",
    "Your battery is running low! Time to recharge, Boss.",
    "Battery warning: Please connect to power to continue using.",
    "Reminder: Your device is low on battery. Plug it in.",
    "Urgent: Charge your device now to avoid shutdown.",
    "Battery alert: Please charge immediately to stay connected.",
    "Attention: Your battery is low! Don't let it die.",
    "Warning: Your device is running low on battery. Connect to power.",
    "Caution: Low battery detected! Please charge soon.",
    "Heads up! Your battery level is low. Time to charge.",
    "Battery alert: Your device needs a charge ASAP.",
    "Notice: Low battery! Please connect your charger.",
    "Warning: Your device is low on power. Recharge it now.",
    "Critical battery alert: Please connect to a power source."
]

lastChanceDLG = [
    "Boss, this is your last chance. Your battery is very low.",
    "Attention: Boss, this is your final warning. Battery is critically low.",
    "Warning: Boss, your battery is almost gone. This is your last chance!",
    "Caution: Boss, this is your last opportunity. Charge your device now!",
    "Boss, your battery is running dangerously low. This is your final chance.",
    "Last call, Boss! Your battery is very low. Charge it ASAP.",
    "Boss, this is it! Your battery is almost empty. Please recharge.",
    "Final alert: Boss, your battery is low. Time to plug in!",
    "Boss, your device is on its last legs! Charge it now.",
    "Urgent: Boss, this is your last chance. Battery level is critical.",
    "Boss, this is your final notice. Battery is running very low!",
    "Warning: Boss, your battery is about to die. Charge immediately!",
    "Boss, it's your last chance! Your battery is dangerously low.",
    "Attention: Boss, your battery is almost out. Recharge now!",
    "Boss, this is your last warning! Battery level is critically low.",
    "Final chance, Boss! Your battery is running low. Charge it soon.",
    "Boss, time is running out! Your battery is very low.",
    "This is it, Boss! Charge your device immediately—battery is low.",
    "Boss, your battery is on its last chance. Plug it in!",
    "Last warning, Boss! Your battery is very low.",
    "Caution: Boss, this is your last opportunity to charge.",
    "Boss, this is your final chance! Your battery needs power.",
    "Boss, urgent! This is your last chance before the device dies.",
    "Warning: Boss, your battery is very low. Charge now!",
    "Final call, Boss! Your device needs charging ASAP.",
    "Boss, your battery is critically low. This is your last chance!",
    "Last chance, Boss! Charge your device before it shuts down.",
    "Boss, this is it! Your battery is almost depleted. Recharge!",
    "Caution: Boss, this is your last chance to plug in.",
    "Boss, your device is low on battery. Time to charge it up!",
    "Urgent: Boss, your battery is running out. Final chance to recharge.",
    "Warning: Boss, this is your last chance to save your device.",
    "Boss, this is your final notice. Charge your battery soon.",
    "Last alert, Boss! Battery is very low. Charge immediately.",
    "Boss, your device is on its last chance! Please charge it.",
    "Attention: Boss, your battery is critically low. Time to recharge.",
    "Final notice, Boss! Your battery is running low.",
    "Boss, this is your last chance to connect to a power source.",
    "Warning: Boss, your battery level is dangerously low. Charge now!",
    "Caution: Boss, this is your last call. Charge your device.",
    "Boss, your battery is almost empty. This is your final chance!",
    "Final warning, Boss! Your device needs charging ASAP.",
    "Boss, this is your last opportunity. Recharge your battery.",
    "Attention: Boss, your battery is low. Final chance to plug in.",
    "Boss, this is your last warning! Charge your device immediately.",
    "Last chance, Boss! Your battery is critically low.",
    "Boss, your device is low on power. This is your final chance!",
    "Warning: Boss, your battery is running very low. Recharge now!",
    "Final alert: Boss, this is your last chance to charge your device."
]


batteryLowDLG = [
    "Boss, let me tell you. Your battery is very low.",
    "Attention: Boss, just to inform you, your battery is critically low.",
    "Warning: Boss, I want to let you know that your battery is almost gone!",
    "Caution: Boss, just so you know, your battery needs charging now!",
    "Boss, I must inform you, your battery is running dangerously low.",
    "Last call, Boss! Just a reminder, your battery is very low. Charge it ASAP.",
    "Boss, just to let you know, your battery is almost empty. Please recharge.",
    "Final alert: Boss, I want to inform you that your battery is low. Time to plug in!",
    "Boss, your device is on its last legs! Just so you know, charge it now.",
    "Urgent: Boss, just to remind you, your battery level is critical.",
    "Boss, this is important! Your battery is very low. Please charge immediately!",
    "Attention: Boss, just to inform you, your battery is about to die.",
    "Boss, I need to let you know, this is your last chance! Your battery is dangerously low.",
    "Final chance, Boss! Just so you know, your battery is running low. Charge soon.",
    "Boss, time is running out! Just to remind you, your battery is very low.",
    "This is it, Boss! Charge your device immediately—your battery is low.",
    "Boss, I must let you know, your battery is on its last chance. Plug it in!",
    "Last warning, Boss! Just to inform you, your battery is very low.",
    "Caution: Boss, this is your last opportunity to charge before it dies.",
    "Boss, just to remind you, this is your final chance! Your battery needs power.",
    "Boss, urgent! Just a heads up, your battery is running out. Final chance to recharge.",
    "Warning: Boss, just so you know, your battery is very low. Charge now!",
    "Final call, Boss! Your device needs charging ASAP. Just to inform you.",
    "Boss, just to let you know, your battery is critically low. This is your last chance!",
    "Last chance, Boss! Just so you know, charge your device before it shuts down.",
    "Boss, this is it! Just to inform you, your battery is almost depleted. Recharge!",
    "Caution: Boss, just to remind you, this is your last chance to plug in.",
    "Boss, your device is low on battery. Just to let you know, time to charge it up!",
    "Urgent: Boss, just to inform you, your battery is running out. Final chance to recharge.",
    "Warning: Boss, just so you know, this is your last chance to save your device.",
    "Boss, I must let you know, this is your final notice. Charge your battery soon.",
    "Last alert, Boss! Just to inform you, your battery is very low. Charge immediately.",
    "Boss, your device is on its last chance! Just so you know, please charge it.",
    "Attention: Boss, just to remind you, your battery is critically low. Time to recharge.",
    "Final notice, Boss! Just to let you know, your battery is running low.",
    "Boss, this is your last chance to connect to a power source. Just so you know.",
    "Warning: Boss, just to inform you, your battery level is dangerously low. Charge now!",
    "Caution: Boss, this is your last call. Just so you know, charge your device.",
    "Boss, just to let you know, your battery is critically low. This is your final chance!",
    "Final alert: Boss, I want to inform you that this is your last chance to charge.",
    "Boss, your battery is below 50%. Just a heads up that it’s time to charge.",
    "Attention: Boss, your battery is below half. Charge soon to keep it running.",
    "Warning: Boss, your battery is less than 50%. It's a good time to plug in!",
    "Boss, just so you know, your battery is below 50%. Recharge when you can.",
    "Caution: Boss, your battery is under half. Make sure to charge it soon.",
    "Boss, your battery is running low! Just so you know, it's below 50%.",
    "Alert: Boss, your battery is now below 50%. Please connect to power."
]

batteryFullDLG = [
    "Boss, your battery is at 100 percent. Please unplug it.",
    "Attention: Boss, your battery is fully charged at 100 percent. Unplug it now.",
    "Warning: Boss, your battery is at full capacity. Time to disconnect!",
    "Caution: Boss, your battery is 100 percent charged. Please unplug it!",
    "Boss, just a reminder, your battery is at 100 percent. Unplug it to save energy.",
    "Final notice: Boss, your battery is full at 100 percent. It's time to disconnect.",
    "Boss, your device is fully charged! Please unplug it to prevent overcharging.",
    "Urgent: Boss, your battery has reached 100 percent. Please unplug it now!",
    "Boss, this is important! Your battery is fully charged. Disconnect it!",
    "Attention: Boss, your battery level is at 100 percent. Please unplug immediately.",
    "Boss, your battery is at maximum capacity. It's time to unplug it.",
    "Caution: Boss, your battery is fully charged at 100 percent. Please disconnect!",
    "Boss, just so you know, your battery is at 100 percent. Unplug to save energy.",
    "Warning: Boss, your device is at full charge. Please unplug it now.",
    "Final alert: Boss, your battery is 100 percent charged. Time to disconnect!",
    "Boss, your battery is fully charged! Please unplug to avoid damage.",
    "Attention: Boss, your battery is at 100 percent. Disconnect it for safety.",
    "Boss, just a heads up, your battery is fully charged. Please unplug it.",
    "Caution: Boss, your battery is at 100 percent. Unplug it to save battery life.",
    "Boss, your battery has reached full charge! Please disconnect it now.",
    "Warning: Boss, your battery is at 100 percent. It's time to unplug.",
    "Final notice: Boss, your device is fully charged. Unplug it for safety.",
    "Boss, this is important! Your battery is at maximum capacity. Unplug now!",
    "Attention: Boss, your battery is fully charged. Please unplug it immediately.",
    "Caution: Boss, your battery is at 100 percent. Please disconnect it!",
    "Boss, just to inform you, your battery is at full charge. Unplug to preserve it.",
    "Warning: Boss, your battery is now at 100 percent. Unplug it!",
    "Final alert: Boss, your battery has reached full capacity. Please unplug!",
    "Boss, your battery is at 100 percent charged. It's time to disconnect.",
    "Attention: Boss, your battery is fully charged. Unplug it now.",
    "Caution: Boss, your battery is at maximum capacity. Please disconnect it.",
    "Boss, your device is fully charged at 100 percent. Time to unplug!",
    "Warning: Boss, your battery is full. Unplug it for optimal performance.",
    "Final notice: Boss, your battery is at 100 percent. Please unplug it.",
    "Boss, just a reminder that your battery is fully charged. Please disconnect it.",
    "Attention: Boss, your battery has reached full charge. Unplug immediately.",
    "Caution: Boss, your battery is at 100 percent. Disconnect it for safety.",
    "Boss, your battery is fully charged! Time to unplug it now.",
    "Warning: Boss, your battery is at maximum capacity. Please disconnect.",
    "Final alert: Boss, your battery is at 100 percent. Unplug it to avoid overcharging.",
    "Boss, your device is fully charged. Please unplug to preserve battery health.",
    "Attention: Boss, your battery is at 100 percent. Time to disconnect it.",
    "Caution: Boss, your battery is fully charged. Unplug it to save energy.",
    "Boss, just so you know, your battery is at 100 percent. Please unplug it now."
]


chargingDLG = [
    "Boss, plugging successful! Your device is charging now.",
    "Great news, Boss! The device is plugged in and charging.",
    "Boss, successful connection! Your device is now charging.",
    "Boss, you're all set! Your device is charging successfully.",
    "Charging complete, Boss! Your device is now plugged in.",
    "Boss, you're good to go! The device is charging now.",
    "Boss, plugging was a success! Your device is charging.",
    "Success, Boss! Your device is now receiving power.",
    "Boss, the connection is successful! Your device is charging.",
    "Boss, your device is plugged in and charging successfully.",
    "Awesome, Boss! Your device is charging now.",
    "Boss, everything's set! Your device is now charging.",
    "Boss, the device is charging successfully. You're good!",
    "Boss, charging initiated! Your device is now plugged in.",
    "Fantastic, Boss! Your device is charging properly.",
    "Boss, connection established! Your device is charging now.",
    "Boss, your device is now charging. Plugging was successful!",
    "Charging started, Boss! Your device is plugged in.",
    "Boss, your device is charging. Connection successful!",
    "Boss, the device is now charging. Plugging successful!",
    "Boss, great job! Your device is successfully charging.",
    "Boss, the charging process has started. Your device is plugged in.",
    "Boss, your device is now connected and charging.",
    "Charging successful, Boss! Your device is plugged in.",
    "Boss, your device is now charging. Connection successful!",
    "Boss, everything's in order! Your device is charging.",
    "Boss, charging successful! Your device is now receiving power.",
    "Boss, you're all set! The device is charging now.",
    "Boss, the connection is successful! Your device is charging.",
    "Boss, successful plugging! Your device is now charging.",
    "Boss, your device is now charging successfully.",
    "Boss, the charging has started! Your device is plugged in.",
    "Boss, your device is plugged in. Charging successful!",
    "Success! Boss, your device is now charging.",
    "Boss, everything is set! Your device is charging now.",
    "Charging complete, Boss! Your device is successfully plugged in.",
    "Boss, your device is now charging. Plugging was successful!",
    "Boss, you're good to go! The device is charging now.",
    "Boss, successful connection! Your device is now charging.",
    "Boss, you're all set! Your device is charging successfully.",
    "Fantastic news, Boss! The device is charging now.",
    "Boss, the connection is successful! Your device is charging.",
    "Boss, your device is charging. Plugging was a success!",
    "Boss, the device is charging now. Connection successful!",
    "Boss, great job! Your device is successfully charging.",
    "Boss, the charging process has started. Your device is plugged in.",
    "Boss, your device is now connected and charging.",
    "Charging successful, Boss! Your device is plugged in.",
    "Boss, your device is now charging. Connection successful!",
    "Boss, everything's in order! Your device is charging.",
    "Boss, charging successful! Your device is now receiving power."
]

batteryPowerDLG = [
    "Boss, your device is unplugged. You're running on battery power.",
    "Attention, Boss! The device is unplugged and using battery power.",
    "Boss, your device has been unplugged. Running on battery now.",
    "Caution, Boss! Your device is unplugged and operating on battery.",
    "Boss, the device is now unplugged. You're on battery power.",
    "Boss, your device is disconnected. You're relying on battery now.",
    "Boss, your device is unplugged. Time to save battery power!",
    "Warning, Boss! The device is unplugged and using battery.",
    "Boss, your device has been unplugged. Running on battery.",
    "Boss, your device is now unplugged. Battery power is in use.",
    "Boss, attention! Your device is unplugged and on battery.",
    "Boss, your device is unplugged. Please conserve battery power.",
    "Caution, Boss! The device is running on battery power now.",
    "Boss, your device is unplugged. Monitor your battery level.",
    "Boss, your device has been unplugged. You're on battery now.",
    "Boss, your device is disconnected. Battery power is active.",
    "Boss, your device is now unplugged. Time to manage battery.",
    "Boss, the device is unplugged. You're using battery power.",
    "Boss, your device is unplugged. Please keep an eye on battery.",
    "Boss, caution! Your device is unplugged and on battery power.",
    "Boss, your device is unplugged. Remember to charge it soon!",
    "Boss, your device is now unplugged. Running on battery.",
    "Attention, Boss! Your device is unplugged and using battery.",
    "Boss, your device is disconnected. Battery power is now in use.",
    "Boss, your device has been unplugged. Monitor your battery.",
    "Caution, Boss! The device is unplugged. You're on battery now.",
    "Boss, your device is unplugged. Conserve battery power!",
    "Warning, Boss! Your device is unplugged and on battery.",
    "Boss, your device is unplugged. Please charge soon.",
    "Boss, your device has been unplugged. Running on battery now.",
    "Boss, your device is now unplugged. You're using battery.",
    "Boss, attention! Your device is unplugged and on battery power.",
    "Caution, Boss! The device is now unplugged. Monitor battery.",
    "Boss, your device is unplugged. Please save battery power.",
    "Boss, your device is now unplugged. Battery is in use.",
    "Boss, the device is unplugged. You're running on battery.",
    "Attention, Boss! Your device is unplugged and using battery.",
    "Boss, your device is disconnected. You're on battery now.",
    "Boss, your device has been unplugged. Time to check battery.",
    "Caution, Boss! The device is unplugged. You're on battery power.",
    "Boss, your device is unplugged. Monitor your battery level.",
    "Boss, your device has been unplugged. You're on battery power.",
    "Boss, your device is unplugged. Please charge soon.",
    "Attention, Boss! Your device is unplugged and running on battery."
]


random_text=[
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir"
]

call_me = [
    "Hello Boss! If you ever need me, just call out, and I'll be there.",
    "Hey Boss! Whenever you need me, just say the word, and I'm ready to assist.",
    "Boss, I'm here for you! Just call my name whenever you need me.",
    "Hello Boss! If you ever require my help, just wake me up with your voice.",
    "Hey Boss! I'm always at your service. Just call, and I'll respond instantly.",
    "Boss, just a word from you, and I'll be up and running!",
    "Hello Boss! Say my name, and I'm at your command.",
    "Hey Boss! I'm listening—just let me know what you need.",
    "Boss, your assistant is always ready. Just summon me anytime!",
    "Hello Boss! A simple call, and I'll be right there for you.",
    "Hey Boss! Need something? Just call out, and I'll handle it.",
    "Boss, I’m always awake for you—just give me a shout.",
    "Hello Boss! Say the word, and I’ll jump into action immediately.",
    "Boss, I’m here to assist you. Just call me, and let’s get started!",
    "Hey Boss! Whatever you need, just wake me up with your voice."
]
